# Generated by Django 5.0.2 on 2024-02-13 14:41

import balance_beam.models.customer
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator("^[A-ZÀ-ÿА-ЯЁ][a-zà-ÿа-яё]*(([^\\S\\n\\t]?(\\'|\\’|-|[^\\S\\n\\t])[^\\S\\n\\t]?)([A-ZÀ-ÿА-ЯЁ]?[a-zà-ÿа-яё])+)*$", 'alphabetic values, apostrophes, hyphens are allowed')], verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator("^[A-ZÀ-ÿА-ЯЁ][a-zà-ÿа-яё]*(([^\\S\\n\\t]?(\\'|\\’|-|[^\\S\\n\\t])[^\\S\\n\\t]?)([A-ZÀ-ÿА-ЯЁ]?[a-zà-ÿа-яё])+)*$", 'alphabetic values, apostrophes, hyphens are allowed')], verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('email_verification_status', models.BooleanField(default=False, verbose_name='email verification status')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(blank=True, help_text='Only numbers in the international format E.164.', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^7[^6,7]\\d{9,15}$', 'Incorrect phone number format.     Please enter a Russian phone number using numbers only')], verbose_name='telephone number')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', balance_beam.models.customer.CustomerManager()),
            ],
        ),
        migrations.CreateModel(
            name='BalanceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_customer', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('operation_type', models.CharField(choices=[('INCREASE', 'Increase'), ('TRANSFER', 'Transfer')], max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('text_error', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_operations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
